apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: gym-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
    template:
      data:
        POSTGRES_USER: "{{ .username }}"
        POSTGRES_PASSWORD: "{{ .password }}"
        POSTGRES_DB: "gym_profile"
        DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@profile-postgres:5432/gym_profile"
  data:
    - secretKey: username
      remoteRef:
        key: gym/dev/profile-postgres-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: gym/dev/profile-postgres-credentials
        property: password
